layout_spectrum: 0.6150701
color:
  saturation: 0.1845878
  brandStrength: 0.2054874
  lightness: 0.3458781
  rhythmicContrast: 0.9759476
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.7644474
name: 'Wellness with Susie '
